version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3003:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx-1.25.4/conf/nginx.conf

  node-app:
    build: .
    environment:
      - PORT=3003


  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nimeth20011002
      - MONGO_INITDB_ROOT_PASSWORD=20011002nimeth 
    volumes:
      - mongodb-volume:/data/db  

volumes:
  mongodb-volume:


  

  